- name : Enable UFW and close all ports
  ufw: state=enabled policy=deny
  become: true

- name : Allow all access to tcp port SSH_PORT, 80 and 443
  ufw: rule=allow port={{item}} proto=tcp
  with_items: [ "22" ,80,443]
  become: true
